### ISSUE TITLE
Modbus writer node fails after update to 2.3.0

### ISSUE THREAD

**Issue by rvdm82** [biancode/node-red-contrib-modbus#71]
After updating to v2.3.0 , all my modbus-write nodes that worked under the previous version now fail with the following error : 

21 Nov 20:51:01 - [error] [modbus-write:RL4-GoDown] TypeError: Cannot create property 'messageId' on boolean 'true'
    at ModbusWrite.<anonymous> (/usr/lib/node_modules/node-red-contrib-modbus/modbus/modbus-write.js:86:29)
    at emitOne (events.js:96:13)
    at ModbusWrite.emit (events.js:188:7)
    at ModbusWrite.Node.receive (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at TriggerNode.Node.send (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at TriggerNode.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/core/89-trigger.js:99:56)
    at emitOne (events.js:96:13)
    at TriggerNode.emit (events.js:188:7)
    at TriggerNode.Node.receive (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at SwitchNode.Node.send (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SwitchNode.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/logic/10-switch.js:159:22)
    at emitOne (events.js:96:13)
    at SwitchNode.emit (events.js:188:7)
    at SwitchNode.Node.receive (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at TriggerNode.Node.send (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:137:22)
    at TriggerNode.<anonymous> (/usr/lib/node_modules/node-red/nodes/core/core/89-trigger.js:99:56)
    at emitOne (events.js:96:13)
    at TriggerNode.emit (events.js:188:7)
    at TriggerNode.Node.receive (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at MQTTInNode.Node.send (/usr/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at /usr/lib/node_modules/node-red/nodes/core/io/10-mqtt.js:341:26
    at MqttClient.handler (/usr/lib/node_modules/node-red/nodes/core/io/10-mqtt.js:245:25)

The msg object sent to the modbus-write node is the following : 
{"topic":"rolluik/rl4/cmd","payload":false,"qos":0,"retain":false,"_topic":"rolluik/rl4/cmd","_msgid":"49e0ea6c.9722a4"}

**Comment by biancode** [comment]
v2.3.2 is a next step for boolean issues
